-   id: csv-formatter
    name: CSV Formatter
    description: "Consistently formats CSV files."
    entry: csv-formatter
    language: python
    files: \.csv$

-   id: scalariform
    name: Scalariform
    description: "Runs scalariform scala formatter."
    entry: pre_commit_hooks/scalariform.sh
    language: script
    files: \.scala$

-   id: scalafmt
    name: scalafmt
    description: "Runs scalafmt scala formatter."
    entry: scalafmt
    language: python
    files: \.scala$

-   id: scalastyle
    name: Check ScalaStyle
    description: "Runs scalastyle scala formatter."
    entry: pre_commit_hooks/scalastyle.sh
    language: script
    files: \.scala$

-   id: js-focused-tests
    name: Javascript Focused Tests
    description: "Searches for any focused Javascript tests in the staged files."
    entry: pre_commit_hooks/javascript/focusedTests.sh
    language: script
    files: \.js$

-   id: prettier
    name: Prettier
    description: "Runs prettier javascript formatter."
    entry: pre_commit_hooks/javascript/prettier.sh
    language: script
    files: \.js$

-   id: scalatest-integration-patience
    name: ScalaTest IntegrationPatience
    description: "Enforces that any ScalaTests that use timeouts also use IntegrationPatience so that tests are not flaky."
    entry: pre_commit_hooks/patience.sh
    language: script
    files: test/.*\.scala$
